#!/bin/bash

# Développeur ....: K3rn€l_P4n1K
# Nom ............: PrimeDB
# Description ....: Fournit un point d'accès à la base de données
# Version ........: 1.0
# Date ...........: dimanche 16 avril 2017, 17:18:18 (UTC+0200)
# Dépendances ....: Sqlite3, installation de PrimeDB

# Fonctionnalité .: Transmet un fichier sql à la base de données
# Intention ......: Formaliser l'accès à la base de données
# Remarque .......: AUCUN

# ===========================
# Copyright 2017 K3rn€l P4n1k
# ===========================
#
# This file is part of primeDB.
#
# primeDB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# primeDB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with primeDB. If not, see <http://www.gnu.org/licenses/>.

# ------------------
# VARIABLES GLOBALES
# ------------------

# Chemin du script
SCRIPT="${0}"

# Nom du script
SCRIPT_NAME="$( basename ${0} )"

# Dossier du script
SCRIPT_DIR="$( dirname ${0} )"

# --------------
# INITIALISATION
# --------------

USAGE="USAGE: ${SCRIPT_NAME} <file.sql>"
DATABASE="${SCRIPT_DIR}/database/data/primeDB.db"

# Si pas de premier argument, on sors du script en affichant l'usage
SQL_FILE=${1?${USAGE}}

# -----------
# TRAITEMENTS
# -----------

cat "${SQL_FILE}" | sqlite3 "${DATABASE}"
